archives:
  - files:
    - UNLICENSE
    - README.md
    - config.example.txt
    format_overrides:
    - goos: windows
      format: zip
builds:
  - main: ./cmd/main.go
    id: "cmd"
    binary: devtome
    goos:
      - linux
      - windows
